benchmark: elasticsearch-query
config:
    deploy:
        node_count: 3
        machine_type: n2-standard-2
    data:
        dataset: glove-100d
        "*shard_count":
            - 1
            - 2
            - 3
        ef_construction: 100
        m: 16
    group:
        "*replica_count":
            - 0
            - 1
            - 2
    query:
        rounds: 1
        k: 100
        batch_size: 1
        "*num_candidates":
            - 100
            - 119
            - 141
            - 168
            - 200
            - 238
            - 283
            - 336
            - 400
            - 476
            - 566
            - 673
            - 800
            - 951
            - 1131
            - 1345
            - 1600
