benchmark: elasticsearch-query
config:
    deploy:
        node_count: 3
        machine_type: n2-standard-2
    data:
        dataset: glove-100d
        "*shard_count":
            - 1
            - 2
            - 3
        ef_construction: 100
        m: 16
    group:
        "*replica_count":
            - 0
            - 1
            - 2
    query:
        rounds: 5
        k: 10
        batch_size: 1
        "*num_candidates":
            - 10
            - 14
            - 20
            - 28
            - 40
            - 57
            - 80
