benchmark: elasticsearch-query
config:
    deploy:
        node_count: 3
        machine_type: n2-standard-2
    data:
        dataset: fashion-mnist
        "*shard_count":
            - 3
            - 6
        ef_construction: 100
        m: 16
    group:
        "*replica_count":
            - 0
    query:
        rounds: 1
        k: 10
        batch_size: 1
        "*num_candidates":
            - 100
            - 200
            - 400
