benchmark: elasticsearch-query
config:
    deploy:
        node_count: 3
        machine_type: n2-standard-2
    data:
        dataset: glove-100d
        "*shard_count":
            - 1
            - 3
            - 6
        ef_construction: 100
        m: 64
    group:
        "*replica_count":
            - 0
            - 1
            - 2
    query:
        rounds: 1
        k: 100
        batch_size: 100
        "*num_candidates":
            - 100
            - 141
            - 200
            - 283
            - 400
            - 566
            - 800
            - 1131
            - 1600
