benchmark: weaviate-serverless-query
config:
    deploy:
        # Set these to the cluster url and api key
        # Or pass deploy.wcs_url=... deploy.wcs_api_key=... as command line arguments
        wcs_url: "https://vdbb-t3kdake1.weaviate.network"
        wcs_api_key: "l4k0kBhb8Yc8QSHWuEnlIMzFuhRIhwlUhdc1"
    data:
        dataset: glove-100d
        ef_construction: 100
        m: 16
    group:
        "*ef":
            - -1
    query:
        rounds: 1
        k: 10
        batch_size: 1 # Weaviate serverless query does not support batched queries
